name: rime2
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - asttokens=3.0.0
  - blas=1.0
  - blosc=1.21.6
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlicffi=1.0.9.2
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - cfitsio=4.6.2
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - cloudpickle=3.1.1
  - comm=0.2.3
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - dav1d=1.2.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - ffmpeg=4.2.2
  - filelock=3.17.0
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gym=0.21.0
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - imagecodecs=2024.9.22
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - intel-openmp=2023.0.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jxrlib=1.2
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.1.4
  - libavif=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcurl=8.14.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libnghttp2=1.67.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopus=1.3.1
  - libpng=1.6.39
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtasn1=4.20.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.4.2
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.5.4
  - packaging=25.0
  - parso=0.8.5
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.4.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - readline=8.3
  - requests=2.32.5
  - scikit-image=0.22.0
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tifffile=2024.12.12
  - tk=8.6.15
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - x264=1!157.20191217
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.0.7
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - alabaster==1.0.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - atari-py==0.2.9
      - attrs==25.3.0
      - babel==2.17.0
      - black==25.9.0
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - coverage==7.10.7
      - cycler==0.12.1
      - dm-control==1.0.34
      - dm-env==1.6
      - dm-tree==0.1.9
      - docutils==0.21.2
      - etils==1.13.0
      - execnet==2.1.1
      - farama-notifications==0.0.4
      - flake8==7.3.0
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - grpcio==1.75.1
      - gym-notices==0.1.0
      - gymnasium==1.2.1
      - h11==0.16.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - hydra-core==1.3.2
      - imagesize==1.4.1
      - immutabledict==4.2.2
      - importlab==0.8.1
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - isort==7.0.0
      - kiwisolver==1.4.9
      - labmaze==1.0.6
      - libcst==1.8.5
      - lxml==6.0.2
      - markdown==3.9
      - matplotlib==3.10.6
      - mccabe==0.7.0
      - metaworld==3.0.0
      - msgspec==0.19.0
      - mujoco==3.3.6
      - mypy-extensions==1.1.0
      - ninja==1.13.0
      - numpy==2.2.6
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - pandas==2.3.3
      - pathspec==0.12.1
      - pluggy==1.6.0
      - protobuf==6.32.1
      - pybullet==3.2.7
      - pycnite==2024.7.31
      - pycodestyle==2.14.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydot==4.0.1
      - pyenchant==3.3.0
      - pyflakes==3.4.0
      - pygame==2.6.1
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pytest==8.4.2
      - pytest-cov==7.0.0
      - pytest-env==1.2.0
      - pytest-xdist==3.8.0
      - pytokens==0.1.10
      - pytype==2024.10.11
      - pytz==2025.2
      - regex==2025.9.18
      - safetensors==0.6.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentry-sdk==2.39.0
      - setuptools==59.8.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - sphinx==8.1.3
      - sphinx-autobuild==2024.10.3
      - sphinx-autodoc-typehints==3.0.1
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sphinxcontrib-spelling==8.0.1
      - starlette==0.48.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomli==2.3.0
      - tqdm==4.67.1
      - transformers==4.56.2
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uvicorn==0.37.0
      - wandb==0.22.1
      - watchfiles==1.1.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wheel==0.38.4
      - wrapt==1.17.3
